### ISSUE TITLE
Porting to Python2

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#1]
Luźne podsumowanie z maila:
- 3to2 ?
- super() - poprawione na uniwersalne wywołania
- coś unicodem trzeba poprawić, bo teraz zauważyłem:
  - fragmenty wyświetlanych łańcuchów wyświetlają się z przedrostkiem u''
  - autocomplete nie działa dla łańcuchów zawierających ogonki

**Comment by emkael** [comment]
Wypchnąłem dziś kilka zmian, które trochę przybliżają do celu.

ac6d5ebbe przesłania `input()` dla Pythona 2.x funkcją `raw_input()`.
e0ac2a81c i 70f771d2a są czysto kosmetyczne i poprawiają wyświetlanie łańcuchów znaków
W końcu -  1278ce86 sprawia, że autocomplete zaczyna działać również w 2.x, ale jest małe "ale".

Problem polegał na tym, że moduł `readline` w 2.x nie przepada za podawaniem mu łańcuchów typu `unicode`, więc konweruję słownik do `bytestring`ów, używając kodowania znaków środowiska użytkownika (żeby nie było później problemów z ich wypisywaniem).
Takie rozwiązanie działa poprawnie (i to całkowicie, z tego co zauważyłem), ale tylko w środowisku unikodoprzyjaznym (testowałem pod Debianem w powłoce w UTF-8).

Z standardowej windowsowej powłoce, w kodowaniu Latin-2, `readline` co prawda wyświetla już poprawnie słownik wszystkich podpowiedzi (bo te są czytane przez ORM jako unikodowe łańcuchy), ale sypie się na porównaniach, jeśli wpisany dotychczas tekst jest niepusty.
Próbowałem konwertować pobrany z klawiatury tekst (zmienna `text` w metodzie `Completer.complete`) do tej samej postaci, co słownik podpowiedzi, ale:
- windowsowa implementacja `readline` (`pyreadline`) co prawda wykonuje poprawne porównanie i uzupełnia wpisany tekst, ale śmieci przy tym na ekranie ostrzeżeniem
- kolejny `[TAB]` po uzupełnieniu robi coś zupełnie niezrozumiałego, bo jest wykrywany jako koniec wprowadzania tekstu i powoduje kolejny z problemów, czyli
- tak pobrany z klawiatury tekst nie jest w stanie być z powrotem przekazany do bazy danych celem wyszukania gracza (rzucany jest wyjątek wskazujący na podwójne kodowanie gdzieś w drodze powrotnej do bazy)

Do tego wpisanie całego nazwiska i imienia z palca, bez użycia uzupełniania, nie znajduje gracza, więc coś jest jeszcze mocno nie tak.

Próbowałem również uruchomić kod pod 3.x pod Windowsem, ale nie mogę znaleźć modułu, który implementowałby MySQLdb dla Pythona 3 pod Windows. Nie testowałem jeszcze przełączenia django na żaden inny engine, ale nie brzmi to jak jakiś problem, bo, w przeciwieństwie do kwestii poruszonych w #2, w docelowym EXE można wkompilować działający zestaw modułów.

**Comment by michzimny** [comment]
Przejrzałem zmiany, nie mam uwag i będę testował dziś dalej na tej wersji ale pod Pythonem 3.

W kodowanie w Pythonie 2 wolałbym nie wchodzić, bo zawsze masę włosów z głowy sobie na to wyrywałem i nigdy dość nie zgłębiłem.

ORM-a jak najbardziej możemy zmienić. Użyłem pierwszego z brzegu, którego najlepiej znałem, a który do tych celów akurat najlepszy nie jest.

**Comment by emkael** [comment]
W takim razie proponuję pozostawić zmiany takie, jakie są, w obecnej gałęzi, i nie kopać się dalej z Pythonem 2.x.

**Comment by michzimny** [comment]
Super, to merguję tę gałąź do mastera.
