### ISSUE TITLE
Obsłużyć problem z połączeniem z MySQL w jakiś sposób human-readable

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#10]
Próba odpalenie z release'u 0.1-rc na angielskim windowsie kończy mi się takim komunikatem jak w tytule.

Odpalam:

> quick_lineup.exe 1 1

**Comment by emkael** [comment]
Wygląda na to, że:
 * przy próbie połączenia do MySQL wystąpił *jakiś* błąd
 * pyinstaller nie spakował tłumaczeń dla connectora MySQL (modułu `mysql.connector.locales`), bo i niby skąd się miał domyślić, że mu będzie potrzebny

Po naprawieniu drugiego punktu, pewnie będzie można przejść do diagnozowania pierwszego :)

**Comment by emkael** [comment]
Rewizja 16b317f dodaje do binarki rzeczone tłumaczenia.

Chcesz, żebym podrzucił Ci skompilowany EXE, chcesz skompilować go sam?

Nie chciałbym podmieniać pliku dystrybuowanego z tagiem 0.1-rc1, po scaleniu gałęzi `mysql-locales` można wydać -rc2.

**Comment by michzimny** [comment]
Możesz podrzucić exe i przygotować release. Niedługo liga! :P

**Comment by emkael** [comment]
https://github.com/michzimny/teamy-quick-lineup/releases/tag/0.1-rc2
