### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Jaom** [michzimny/teamy-quick-lineup#17]
Chyba się zdezaktualizowało skoro udało się zwarpować ql

**Comment by emkael** [comment]
Sposób użycia się nie zmienił, od czasu pobierania niepodanych parametrów (#14) README zostało zaktualizowane o tę informację.

**Comment by Jaom** [comment]
Instalacja jest niepotrzebna jeśli używa się execa, prawda?
Już się też nie wpisuje: python quick_lineup.py
Po pierwszym uruchomieniu tworzy się .config, w którym trzeba podać dane. User może się zdziwić, że configuration mówi "Set MySQL settings in config.json." gdy nie ma w ogóle takiego pliku (przed pierwszym uruchomieniem).

**Comment by michzimny** [comment]
Myślę, że trzeba trochę skorygować. Najpierw jakaś sekcja dla zwykłego usera - informacje, o których pisze Marcin. Potem mogą być szczegóły dla deweloperów, np. że potrzebny jest pip.

**Comment by emkael** [comment]
Można też w sumie wrzucić zaktualizowane README do paczki, która jest przypięta w release.

**Comment by michzimny** [comment]
done

**Comment by michzimny** [comment]
done
