### ISSUE TITLE
Jak się nie poda nazwy bazy danych w settingsach to program mógłby interaktywnie pytać

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#19]
Podobnie jak pyta o rundę i segment. Przydatne, gdy prowadzi się więcej niż jeden turniej.

**Comment by emkael** [comment]
#20

**Comment by emkael** [comment]
Chyba że życzysz sobie podpowiadania `TAB`em istniejących baz danych - ale to nie umiem :(
