### ISSUE TITLE
Wyrzucenie konfiguracji bazy do niewykonywalnego pliku

### ISSUE THREAD

**Issue by emkael** [michzimny/teamy-quick-lineup#2]
Z poważniejszych rzeczy projektowych, jakie zauważyłem w kontekście kompilacji do EXE, to że konfiguracja bazy danych ustalana jest w jednym z modułowych plików .py.

Docelowo jest to niepożądane (z chwilowego braku silniejszego określenia), bo nie chcemy wkompilowywać (czy to w ogóle jest słowo?) konfiguracji w EXE.

Jak zabiorę się za konfigurację PyInstallera, przepiszę settings.py tak, by konfiguracja była czytana z jakiegoś niepythonowego pliku.
Może do tego jakieś pobieranie konfiguracji jawnie od użytkownika w przypadku nieobecności takiego pliku?

(Czuję się również zagubiony w kwestii języka obowiązującego w Issues - zgłoszenie #1 ma tytuł po angielsku, a treść po polsku :D)

**Comment by michzimny** [comment]
+1

Dyskutować możemy po polsku i nazywać tickety po polsku. Termin "porting" akurat prościej było wyrazić po angielsku :P

Ale ogólnie jestem raczej zwolennikiem komentowania kodu i commitów po angielsku, a już tym bardziej, że to jest dodatek do anglojęzycznego softu! :D

**Comment by michzimny** [comment]
To chyba lepiej zrobić po #4.

**Comment by emkael** [comment]
Zrobione w gałęzi `pyinstaller`.
