### ISSUE TITLE
Zapakowanie do EXE

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#3]
To chyba nasz główny cel.

Blokerem dla tego zadania jest na pewno #2, ale czy koniecznie #1? Chyba skoro pakujemy do EXE to już bez znaczenia, którego Pythona zapakujemy, a skoro w jednej wersji program działa ok, a w innej ma problem, to może lepiej pakować z tą wersją Pythona, w której działa? ;)

Chyba, że przeszkodą jest to, że mamy tylko ekspertyzę py2->exe, a py3 już nie? Ale może dalej prościej będzie zgłębić problem py3->exe niż #1.

**Comment by michzimny** [comment]
Jeśli odpuszczamy #1 to mamy takie blokery:
- #2 
- #4, bo w mailu pisałeś o problemach z pakowaniem django do exe

Coś jeszcze?

**Comment by emkael** [comment]
Nie wiem, czy trzymanie binarki w repozytorium to dobry pomysł, ale na razie jest tu wrzucona. Gałąź `pyinstaller` zawiera wszystko, czego trzeba do kompilacji do EXE pyinstallerem.
Do tego dorzuciłem trochę globalnej obsługi wyjątków oraz parsowanie parametrów linii poleceń przez `argparse`.

**Comment by emkael** [comment]
Binarka usunięta z repozytorium, wrzucona w tag: https://github.com/michzimny/teamy-quick-lineup/releases/tag/0.1-rc1
