### ISSUE TITLE
Zmiana ORM na jakiś przyjemniejszy do pakowania do EXE

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#4]
@emkael - jaki? Znasz jakiś, żeby wymienić?

**Comment by emkael** [comment]
Trochę dłubałem w SQLAlchemy, ale mogę powalczyć jeszcze z py3->exe, może będzie mniej problematyczne niż wpięcie innego ORM.

Chwilowo w środowisku windowsowym nie mam py3, bo dość intensywnie pisałem bidding-data (w py2) i coś mi tam bruździło. Kwestia kilku dni, żeby sprawdził pod py3 pyinstallera albo py2exe (którego "2" to zdaje się "to", a nie "two").

**Comment by emkael** [comment]
Zmiana ORM okazała się nie dość, że bardzo upierdliwa, to jeszcze kompletnie zbędna. Gałąź `pyinstaller` zawiera konfigurację pyinstallera z, najwyraźniej, wszystkimi niezbędnymi importami.
