### ISSUE TITLE
Udokumentować jak to odpalić pod natywnym Windowsem i Pythonem 3

### ISSUE THREAD

**Issue by michzimny** [michzimny/teamy-quick-lineup#5]
Marcin sygnalizował problemy z zależnościami (readline?). Jeśli #3 zajmie jeszcze trochę czasu, to może krótki opis, jak to odpalić pod Windowsem? Chyba, że #3 będziemy mieli niedługo to już nie ma co i mogą "klienci" poczekać jeszcze chwilę na exe.

**Comment by michzimny** [comment]
Nieaktualne. Rozwiązanie znane, cytuję Marcina:

>  Potrzebny był downgrade z 3.5 do 3.4 (bo do 3.5 nie ma connectora mysql od oracla), a potem instalacja pyreadline coby brak readline rozwiązać.

**Comment by Jaom** [comment]
TODO: dodać powyższe do readme?

**Comment by michzimny** [comment]
Słusznie. Instalacja pyreadline wystarczy

> pip install pyreadline

?

Skąd instalacja connectora?

**Comment by emkael** [comment]
https://dev.mysql.com/downloads/connector/python/

A może po prostu wrzucić jakieś alternatywy do requirements.txt? PIP w ogóle obsługuje tego typu składnię (pakiet x lub y, tudzież odpowiedniki pakietów wirtualnych w dystrybucjach linuksów)?

**Comment by emkael** [comment]
Aha, no i instalacja connectora wymaga jeszcze zmiany `engine` w konfiguracji, więc chyba i tak warto opisać.

**Comment by Jaom** [comment]
Ja się nie znam na PIP i nie mam teraz ochoty się poznawać. I tak w ogóle smutno mi, że nie mam dość samodyscypliny, by stwierdzić, że najpierw pilniejsze rzeczy, a potem odpisywać na githubie. :P
Niemniej pomysł bardzo dobry. Weźmy się i zróbcie? :-)

**Comment by michzimny** [comment]
Nie rozumiem z tym requirements.txt. Pip przecież i tak nie zainstaluje nam wymaganych paczek systemowych, prawda?

Na czym polega zmiana engine? Może dopiszesz, co uważasz: #6

**Comment by Jaom** [comment]
3 . linijka w settings.py:
`'ENGINE': 'mysql.connector.django',`

**Comment by emkael** [comment]
PIP nie zainstaluje paczek systemowych, ale może można mu podać coś w stylu "spróbuj zainstalować readline w wersji X labo pyreadline w wersji Y". Co prawda nie używałem, ale ponoć `requirements.txt` jest dokładnie po to - żeby nie instalować z palca wszystkich bibliotek, tylko podać ten plik jako parametr dla PIPa.

W `settings.py` dokładnie to, co pisze Marcin - instalacja connectora Oracle'a wymaga zmiany konfiguracji.

**Comment by Jaom** [comment]
Ciekawostka - jak w poprzednim commencie nie dam spacji między trójką i kropką, to w preview wygląda to tak samo (również bez rzeczonej spacji), natomiast po kliknięciu "comment" GitHub udowadnia, że ma downa.

**Comment by Jaom** [comment]
1. linijka w settings.py:
   'ENGINE': 'mysql.connector.django',

**Comment by michzimny** [comment]
> Co prawda nie używałem, ale ponoć requirements.txt jest dokładnie po to - żeby nie instalować z palca wszystkich bibliotek, tylko podać ten plik jako parametr dla PIPa.

Jakieś namiary na takie rozwiązanie? Możemy zrobić osobne pliki requirementów per platforma, ale takich warunków w ramach jednego pliku to nie widziałem nigdy.

**Comment by emkael** [comment]
Proponowane zmiany dokumentacji w gałęzi `requirements`.

**Comment by emkael** [comment]
Z racji tego, że w gałęzi `pyinstaller` jest kompilowalny kod (oraz binarka), co robimy z aktualizacją dokumentacji?
